LedFx/LedFx

.devcontainer/Dockerfile, .devcontainer/Dockerfile.pip, .devcontainer/dev-apt-install.sh, .devcontainer/devcontainer.json, .vscode/tasks.json
- Update Dockerfile to a multi-stage build
- Add dev-apt-install.sh script to speed up docker build
- Add default vscode extensions and settings for all dev environments
- Add task to build and edit the docs with livehtml
=> Update Dockerfile, devcontainer script, settings

README.rst
Just while we're waiting, update readme so we have a better landing that points to our repo...
=> Update README for Landing

frontend/src/components/DisplaySegmentsDialog/AddSegmentDialog.js, frontend/src/components/VirtualComponents/DialogAddSegment.js, ledfx/displays.py
* Can't add match names of many devices in virtuals
* 'Nonetype' object has no  attribute 'is_active'
=> Fix 2 issues

ledfx/api/effects.py, ledfx/api/scenes.py
* Added clear_all_effects operation to effects API
* Fixed bug in GET method throwing a HTTP 500 error in effects API
* Added deactivate operation to scenes API
=> Added and fixed some operations to effects and scenes APIs

docs/installing.rst
Update docs for Apple Silicon M1 install for dev branch
=> Update docs for Apple Silicon M1 install for dev branch

ledfx/api/__init__.py, ledfx/api/config.py, ledfx/api/schema.py, ledfx/api/virtual_effects.py, ledfx/devices/__init__.py, ledfx/effects/__init__.py, ledfx/effects/audio.py, ledfx/effects/melbank.py, ledfx/virtuals.py, midi_mapper.py
make the new branch more portable to older systems. Not sure if I cought all, but at least it's a beginning.
=> Make branch runable on python 3.8

ledfx/effects/bar.py
initial implementation of skipping beats in bar effect
=> option to skip every odd or even beat in bar effect

docs/installing.rst
updating Apple Silicon install documentation
=> updating Apple Silicon install documentation

ledfx/api/virtuals.py, release.py
Want to get clean so I don't miss my own...
=> Linting clean up

ledfx/__main__.py, ledfx/api/virtual_effects.py, ledfx/api/virtual_presets.py, ledfx/devices/wled.py
This will need a careful look if I am breaking intent
Builds up as new effects are activated, so should be extensible
Self heals existing configs so no need to throw away old configs
IF YOU TEST BACK UP YOUR CONFIG FIRST, JUST IN CASE!!!
I need good eyes on this in case I am doing naughty things on data access!
Extensive testing on my end to break it, and it shattered a lot until I got it clean
=> Fixed effect config save, added per effect save

ledfx/effects/math.py, ledfx/effects/melt_and_sparkle.py, ledfx/effects/water.py
Melt and Sparkle is based on melt, with the addition of strobe flashes to add some sparkle.
Water is based on a simple water simulation, with bass, mids, and high intensities causing configurable-sized ripples in the liquid.
=> Two new effects: "Melt and Sparkle" and "Water"

ledfx/presets.py
wanted to look at what it would take to add reset to this new effect, and found the existing framework.
Added the reset clause
=> add reset clause for melt_and_sparkle

ledfx/presets.py
Went through all effects, this is the only other reset button missing
=> add reset clause for water

.gitignore, ledfx/integrations/__init__.py
Adds an enum to integrations class for better readability. Also adds .venv to .gitignore file.
=> Use enum in integration

ledfx/integrations/__init__.py
Use IntEnum instead to avoid serialization problem.
=> Fix Enum not serializable

ledfx/effects/power.py
Added sliders to control the decay rate of the bass bar and sparks to the power effect, following the way it has been implemented in the real strobe effect.
=> Decay rate settings for the power effect

.github/workflows/publish-release-pypi.yml
Used Secret is already added to the repo secrets
=> Trigger HomeAssistant Build

ledfx/effects/scan.py, requirements.txt
More functional effect based on scanning eye effect, using filter power to accelerate scan rate
=> Scan Effect

ledfx/effects/pitchSpectrum.py
Replaces the slow for loop with vector operations
=> Replace pitchspectrum for loop with numpy vector operation

ledfx/effects/scan_multi.py
Built on top of scan
Run a scan for Low, Mid and High power.
Blend the results.
V Nice, very happy with it
=> Multi Scan Lows, Mids and Highs

ledfx/effects/pitchSpectrum.py
This refactors one of our oldest effects to add a render function and remove pixel logic out of the audio data updated method.
It should fix https://github.com/LedFx/LedFx/issues/349
=> Add a render function to pitchspectrum

ledfx/effects/scan_and_flare.py
Turned out very different from what I was expecting and took a lot longer to implement Needs to be seperate to scan or it all gets too complicated
Generates flares off the back of the scan that die out over time, brightness and speed. Tried a flicker effect but it didn't look good, so left as smooth die off
Lots of sliders...
=> Scan and Flare

ledfx/__main__.py, ledfx/utils.py, setup.py
Pyupdater project is dead - time to move on.
=> Remove pyupdater automated updates

hiddenimports.py, ledfx/effects/metro.py, ledfx/utils.py, requirements.txt, setup.py
Stub graph dumping
Leave all code in utils.py under comment blocks
Hide capture key
=> Remove Bokeh dependency

requirements.txt, setup.py
tested that launchpad runs happily on windows only
NEEDS FIX from upstream rtmidi see - Now in 1.5.3
https://github.com/SpotlightKid/python-rtmidi/issues/149
Ready for review / test / merge
=> bump rtmidi to 1.5.3

README.rst
Updated Readme with links to the new builds and links to the newly updated documentation
Edit:
Here's the rtd link
https://ledfx--403.org.readthedocs.build/en/403/
=> Updated Readme with links to latest builds

ledfx/effects/bands.py
Tested against poisoned ledfx.cfg from discord #help_and_support as well as various local trivial reproductions
https://discord.com/channels/469985374052286474/785654321055531078/1126149879077556294
=> Protect bands from pixel_count < band_count

README.rst, docs/developer.rst
Updated links in the readme and where to get the latest dev
=> What's Updoc?

README.rst
Get all images from the same place...
=> Point readme.rst at topology diagram now in github

ledfx/devices/launchpad_lib.py
Speculative attempt at using rapid led update
If this does not work, then just flip line 2025 back to 'if True"
Attempts to reset each frame with a channel 1 write to matrix led 0 off, then use channel 3 writes to set two leds at a time according to current interpretation of the manual
LED mappings may be well off, but if we get basics working we can fix that with pixel effect to look closer
=> attempt number 3 at rapid led

docs/api.rst, docs/conf.py, docs/requirements-docs.txt
Add sphinx-toolbox specifically for collapse
Add css directive to five some head space above rubric
Give examples in scene api documentation including expandable section on new specific virtuals support
https://ledfx--418.org.readthedocs.build/en/418/api.html#api-scenes
=> Update scenes api doc

docs/api.rst, ledfx/api/virtuals_tools.py, ledfx/devices/__init__.py, ledfx/devices/launchpad_lib.py, ledfx/effects/temporal.py, ledfx/virtuals.py
Now ready for integration testing
See Calibration and Highlight section under
https://ledfx--432.org.readthedocs.build/en/432/api.html#api-virtuals-tools-virtual-id
Tested via front end provide by blade
Current color scheme for calibration blocks is 
RGBYCM
With white for highlight
=> First cut of calibration tools

docs/api.rst, docs/configuring.rst, docs/developer.rst
Windows dev notes for backend
Tweak in calibration api
DDP protocol default comments in configuration for WLED
Output at 
https://ledfx--445.org.readthedocs.build/en/445/
=> win backend dev + other

docs/api.rst, ledfx/api/virtual_tools.py, ledfx/api/virtuals_tools.py, ledfx/virtuals.py
See docs "oneshot" section of 
https://ledfx--447.org.readthedocs.build/en/447/api.html#api-virtuals-tools-virtual-id
Now supports 
.../api/virtuals_tools for all active virtuals
.../api/virtuals_tools/<virtual_id> for specific virtual
=> Oneshot virtual override implementation

ledfx/api/find_launchpad.py, ledfx/api/find_openrgb.py, ledfx/effects/bar.py
Clear the pixel space before rendering the bar, missing from the code present in the original version
We still have glitch to track down as discussed in
https://discord.com/channels/469985374052286474/1138633955256586311/1138645959769866351
=> Fix Bar effect, part 1

docs/osc.rst
Now changed the pro's and cons of the All_To_One send type
=> Forgot to fully update osc.rst

ledfx/effects/bands_matrix.py, ledfx/presets.py
This enables to flip along the other axis.
E.g my led strip is wired the other way round
=> add horizontal flip option for bands_matrix effect

docs/api.rst, ledfx/api/get_nanoleaf_token.py
Improve error when not in pairing
=> add nanoleaf auth docs

ledfx/devices/artnet.py, poetry.lock, pyproject.toml
This seems to work but has issues with device shutdown - we don't seem to be triggering **any** device's deactivate function when the effect/virtual that they belong to are deactivated, which means the for loop continues and causes issues.
We'll need to figure that out, but this is a base that "works"-ish.
=> Add Art-Net device type

ledfx/api/device.py, ledfx/api/effect.py, ledfx/api/integration_qlc.py, ledfx/api/integration_spotify.py, ledfx/api/integrations.py, ledfx/api/ping.py, ledfx/api/presets.py, ledfx/api/specified_device_status.py, ledfx/api/virtual.py, ledfx/api/virtual_effects.py, ledfx/api/virtual_presets.py, ledfx/api/virtuals.py, ledfx/api/virtuals_tools.py
First pass of updating the API errors.
I don't think this breaks anything, just makes the errors more verbose (and accurate in some cases)
=> Cleanup API Errors

ledfx/core.py, ledfx/mdns_manager.py
Probably don't name the file the same name as the library you're trying to import, whoops.
=> Rename zeroconf to mdns_manager

ledfx/effects/gifbase.py, ledfx/effects/gifplayer.py, ledfx/effects/keybeat2d.py, ledfx/effects/template2d.py
Also fix up a crash in keybeat if diag2 is on at start
Remove unwanted gradient class from template2d and keybeat
tested against both keybeat and gif effect
check keybeat with diag2 true on startup does not crash
eyeball different artifacting from different resize options
=> Added GifBase class to inherit resizing

ledfx/presets.py
added two extra key frames, that could be seen to be missing using the new frame picker UX
=> improve caddy keyframes

.github/workflows/test-build-binaries.yml
Should help with keeping sentry organised
=> feat: Add Sentry release notification workflow

.github/renovate.json
Updates renovate config - should allow renovate to work.
=> fix: Update renovate dep manager with additional helpers

.github/workflows/test-build-binaries.yml
Prepend ledfx to version string
=> build; Update sentry version format

.github/renovate.json
Update the schedule in the renovate.json file to run every weekend instead of every week.
=> Update schedule in renovate.json

ledfx/consts.py, pyproject.toml
This pull request updates the project version to 2.0.96 in prep for release.
=> Bump project version to 2.0.96

ledfx/devices/__init__.py
Fixes https://github.com/LedFx/LedFx/issues/924
=> Fix: Allow multiple artnet universes for same device IP

ledfx/effects/audio.py
This pull request fixes an issue where the code was not handling the case when there are no audio input devices available. It adds a check to ensure that there are valid audio input devices before using them for audio reactive effects. This prevents crashes.
credit: whoinow: https://discord.com/channels/469985374052286474/1254154163953074239/1254236054098018326
=> fix: Improve audio input device handling when no devices exist

uv.lock
Dependabot maimed the lockfile.
I have rerun uv sync and uv lock --upgrade to upgrade and relock.
=> Update dependencies to latest versions and relock

docs/developer.md
Correct reference from poetry to uv
=> Docs: uv docs tweak for pytest
