LedFx/LedFx

- README.rst
ESP8266 and ESP32 modules do not support 5ghz WiFi so I can see this causing some confusion for someone trying to follow the quick start guide.
> Remove refrence to 5ghz WiFi

- ledfx/devices/e131.py
Converting sent sACN data from numpy "np.int64" array to python list to support newer versions of the sACN library, since it now requires all data sent to be of the normal python "int" type
> Convert sACN data from numpy array to python list

- frontend/src/components/DeviceConfigDialog/index.jsx
Fixes issue where editing or adding a device would silently fail in Firefox.
> Prevent default action of device add/edit form

- ledfx/displays.py
I stumbled upon a problem of not getting full 60fps or 90fps when I set it in device settings. This PR fixes timing issues when some functions take longer than expected.
> Exact timer intervals for every frame

- requirements.txt
- setup.py
Allows to build ledfx on newer systems
> Allow zeroconf dependency >= 0.30.0 since it fixed the windows bug

- ledfx/api/audio_devices.py
- ledfx/effects/audio.py
With these changes I can visualize my jackd dj software mixxx runnig at 96000 pipline.
Iterate over all portaudio apis and collect devices.
Save devicename and index and try to find the device with the same
name on the same api when opening. Since device indexes are very unstable, especially
with jackd.
Set proper fft/rate values when devices use more then 44000 sample rate.
> Add support for all portaudio apis

- ledfx/devices/adalight.py
- ledfx/devices/packets.py
- ledfx/devices/udp.py
- ledfx/devices/wled.py
`devices/packets.py` contains builder functions for WARLS, DRGB, DRGBW, DNRGB and Adalight (will add e1.31 and DDP soon™) 
UDP packets info here: https://kno.wled.ge/interfaces/udp-realtime/
All packet building should be faster because they've been converted to vectorised functions instead of the current for loops (thanks not_matt for your numpy help)
This also changes the UDP and WLED device schema, so I think new configs will be required?
This is also fixes the issue that you can't use more than 490 pixels using WLED UDP, as WLED UDP now defaults to DNRGB (which supports multi-packet updates)
Lastly, I have built `adaptive_smallest`, a udp option for strips smaller than 255 to calculate if a WARLS or DRGB packet will be smaller, per frame update, to reduce WIFI traffic. (though, there …
> Introduce packet builder functions for devices

- ledfx/devices/__init__.py
- ledfx/devices/adalight.py
- ledfx/devices/ddp.py
- ledfx/devices/e131.py
- ledfx/devices/open_pixel_control.py
- ledfx/devices/rpi_ws281x.py
- ledfx/devices/udp.py
- ledfx/devices/wled.py
- ledfx/utils.py
Create base `UDPDevice` and `SerialDevice` that devices (like the WLED UDP Realtime, DDP, and Adalight) can inherent from. This should remove the amount of work/boilerplate that is required to add support for new devices.
(eg. if someone has a new serial device they want to add, they can inherent `SerialDevices` and all they need to write is `def flush()`
I have also moved the `name` and `pixel_count` schema attributes to the base `Device` class, since it should be a completely shared attribute.
I plan to create a base `TCPDevice` class as a foundation for TCP devices Soon™
> Base UDPDevice and SerialDevice classes

- ledfx/devices/udp.py
new `udp.py` config option: `minimise_traffic`
When selected, `UDPRealtimeDevices` will not send an update if a frame hasn't changed since last frame.
(it still sends a frame regardless of change every timeout/2 seconds to keep WLED connection/control active)
> option to not send unchanged frames

- ledfx/devices/openrgb.py
- ledfx/devices/packets.py
- requirements.txt
- setup.py
I don't have any RGB peripherals so only tested using below config into `WLED`:
```json
"LEDStripDevices": {
"devices": [
{
"port": "/dev/ttyUSB0",
"baud": 115200,
"num_leds": 21,
"protocol": "adalight"
}
]
}
```
Code checks to confirm the selected device supports 'direct' mode, which is suitable for high fps streaming.
Code uses `openrgb-python` from pypi, but uses my own implementation to build the RGB packet.
PR means LedFx now supports:
https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/Supported-Devices
> Openrgb device

- ledfx/devices/__init__.py
Current implementation of OpenRGB protocol allow to add only one device from same ip address this is just same approach like adding E1.31 device with multiple universes
> Allow adding multiple OpenRGB devices from same ip address

- LICENSE.txt
In short, this change would mean someone can't distribute a propriety modified version of LedFx. 
We're an open source project, and we expect any project that uses LedFx to also be open source. 
This protects LedFx - For example, preventing a large company from developing and profiting from LedFx without sharing their modifications.
> Update license to GPL

- ledfx/devices/__init__.py
- ledfx/devices/openrgb.py
Fix issue about having multiple devices with same name like RAM stick 
ref https://discord.com/channels/469985374052286474/785654321055531078/944763746503499828
Device ID is list of the devices in OpenRGB interface 
or it can be get from openrgb-python module
```py
import openrgb
from openrgb import OpenRGBClient
client = OpenRGBClient('localhost', 6742)
print(client)
print(client.devices)
```
> Add OpenRGB devices by ID

- ledfx/effects/gradient.py
Shifting axis=0 makes it look more like a strobe, axis=1 produces expected result
> Fix gradient roll

- ledfx/virtuals.py
Should address https://github.com/LedFx/LedFx/issues/233
Two issues
Transitions are created for a transition with zero time, but the mechanism to clear transitions is protected from zero transition time in the config
Don't create a transition when it should be immeadiate
Secondly don't test the config during transition processing, only at transition creation
Otherwise, transitions can be left orphened as the config can change async from the active transition
> Issue 233 divide by zero on transitions

- ledfx/effects/__init__.py
- ledfx/effects/audio.py
- ledfx/virtuals.py
See https://github.com/LedFx/LedFx/issues/235
rain effect has concurrent access risk of the render data from two seperate threads  Calls into numpy np.flatnonzero(self.drop_frames) does an integrity check on the data and will panic if the data is changed between enter and exit 
`Traceback
Exception in thread Thread-3 (thread_function):
Traceback (most recent call last):
File "C:\Users\atod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()
File "C:\Users\atod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\atod\PycharmProjects\LedFxbrf\ledfx\virtuals.py", line 367, in thread_function
self.assembled_frame = self.assemble_frame()
File …
> 235 audio render crash

- ledfx/devices/wled.py
Seeing crashes on startup with multiple WLED controllers, now running 4 x athom and 1 x pixel stick
Stack trace below, which is a trap to check that the pixel render frame is the same size as the subdevice
https://github.com/LedFx/LedFx/blob/main/ledfx/devices/e131.py#L122
`
if data.size != self._config["channel_count"]:`
However, could reproduce what looked like one device using the config of another.
This was actually due to code in setup_subdevice which is a reference, not a copy to the class level single instance variable DEVICE_CONFIGS
https://github.com/LedFx/LedFx/blob/main/ledfx/devices/wled.py#L43
as later code makes changes to the content of config,
https://github.com/LedFx/LedFx/blob/main/ledfx/devices/wled.py#L84
`
config = self.DEVICE_CONFIGS[self._config["sync_mode"]]`
its a …
> Aggressive frame flush crash on multiple device startup

- ledfx/effects/__init__.py
Caused by rework to defend data from concurrent manipulation when _render was introduced
> Add empty _render method to prevent crash on effect deactivate.

- ledfx/virtuals.py
If physicals such as led count has changed on a virtual config, then skip it rather than excepting
Application will still launch and good configs will run, bad configs will refuse to launch effects with an existing front end warning. Delete device and rediscover to fix the config
Segments in span / copy virtuals will also get cleared if larger than physical device Prior behaviour was to just crash out, so you would have to hand repair your config if you reduced number of leds on a device This could be more graceful and auto repair, but its an 80 / 20 I would live with "delete the bad device via the UX"
[ERROR   ] ledfx.virtuals                 : Invalid segment pixels: (0, 49). Device 'WLED5' valid pixels between (0, -1)
[WARNING ] ledfx.virtuals                 : Virtual Segment Changed. …
> Harden config load for mutated device

- ledfx/effects/audio.py
- ledfx/virtuals.py
Looking at the way that the class audioInputSource behaves, it looks like on adding an effect for the first time, we get 6 audioAnalysis callbacks added into self._callbacks AND a callback for the effect itself AudioReactiveEffect
Therefore when an effect is shut down, it only kills its own AudioReactiveEffect callback and count never gets below six
This check for should I shut down audio will therefore never fire
https://github.com/LedFx/LedFx/blob/main/ledfx/effects/audio.py#L312
> Last effect unsubscribe does not stop audio

- ledfx/effects/temporal.py
- ledfx/virtuals.py
Add an extra sleep trap on reactive threading loop when sleep is higher resolution than expected
Due to some audio sources under the covers changing the behaviour of sleep, the monotonic resolution is not the actual sleep resolution
Trap when we don't sleep enough compared to the implied minimum resolution by a gross margin, and then impose an extra sleep to make up to ~monotonic resolution single quantum
In scenarios where there is a high resolution monotonic, then frame sleeps will be multiples of monotonic resolution so code will remain passive
> Fix crazy frame rates on switching to some audio sources

- ledfx/effects/fade.py
- ledfx/effects/gradient.py
- ledfx/effects/rainbow.py
- ledfx/effects/singleColor.py
Temporal behavior mutated when audio reactive was refactored ~2 years ago.
This is the cleanest fix without digging deeper.
add empty on_activation() to each temporal inherited class, as the temporal class registers the thread, and with no on_activation() method in the child, base class method walking for on_activation() will call into temporal parent class again and double register the effect, leading to two threads running for each temporal.
This thread creation is the equivalent of the audio registration for reactive, the behavior there is sane. For audio reactives the audio buffer incoming is the equivalent.
This is a side effect of rework in effect __init__.py that implemented base class walking.
> Fix double threads on temporal

- ledfx/effects/melt_and_sparkle.py
Fixes an issue where setting the strobe width too high in the melt and sparkle effect caused a crash. Changed strobe width to use a float, and gave it a low default value to hopefully be at 1 pixel when starting out. Modified how position is calculated to avoid a crash if the strobe effect is set to 100%.
Closes #252
> Fix a crash when strobe_width out of range

- ledfx/effects/melt_and_sparkle.py
Fixes for Melt and Sparkle
* Constrain strobe width to absolute pixel count
* fix class name
* fix queue might be removed before hsv_render is done being called
fixes https://github.com/LedFx/LedFx/issues/252
> Fixes for Melt and Sparkle

- ledfx/__main__.py
- setup.py
I don't think we need to send yappi out/expose performance logging to the public.
We can use scalene or austin if required for dev setup.
> Remove yappi

- ledfx/virtuals.py
Fix remaining bare render call to wrapper _render that enforces data mutex
Transition renders were not protected in the last fix
Much smaller window of opportunity, but managed to trigger it.
> Fix remaining concurrent data access crash

- ledfx/effects/temporal.py
- ledfx/utils.py
- ledfx/virtuals.py
Rework monotonic / performance counter code to be adaptive to the python version in runtime
Improve protection code for < 3.11 and windows switching sleep clock resolution under the covers
This code will now just take best advantage of the OS / Python version it happens to be on
> Python version sleep management for effects

- ledfx/api/virtual_tools.py
- ledfx/api/virtuals_tools.py
- ledfx/virtuals.py
http://localhost:8888/api/virtuals_tools
http://localhost:8888/api/virtuals_tools/MY_DEVICE_ID
with a body of 
{
"tool": "force_color",
"color": "black"
}
Will stuff the buffer space for that device with the requested color, even if device is not active
for the bare call without a device id specified, all real devices will be color stuffed, so it is easy to blank all devices in one call
Any running effects will overwrite, but this can be used to stuff with "black" so that following changes to segments are distinct
Consider automating black back fill for all all impacted physical devices when a virtual segments configuration is changed
> new restapi endpoint for tools / force_color

- ledfx/api/config.py
- ledfx/effects/energy.py
Fix up random color selection from default OR user
Maybe missing the correct usage of collections but this is the only way I could get it to work!
Quoting from discord
Well I have a fix for the color cycler crash on the Energy effect, feels like I read a lot about python abc ( abstract base classes ) and know less than when I started. I could not get the supposed values() method to do anything sensible on the colors collection, I suspect it is not implemented, and I just don't know how to fix that bit. So for now I have leveraged the get_all() method which does exist, merging the default and user defined colors ( which I don't know if anyone uses ) and then mangle them towards the numpy choice function as a list, and finally translate it into a color type that the following code can …
> Fix crash on enable of c cycler in Energy effect

- ledfx/devices/wled.py
Add port key into the DDP device configs. It is a default required key when running code in
https://github.com/LedFx/LedFx/blob/main/ledfx/devices/ddp.py#L61
I am not aware if this is supposed to be editable, but seen to work!
Switch to DDP in edit device / config / sync mode to reproduce failure
Now works end to end
> Fix DDP support in edit device / config / sync mode

- ledfx/api/scenes.py
The Scene API error message for missing Scene IDs was incorrect - the field should be "id" rather than "scene_id".  This pull request corrects that.
> Corrected Scene API ID field name in error messages for put/delete.

- ledfx/effects/__init__.py
Cap minimum for sigma in _gaussian_kernel1d() to prevent -0.5 / sigma * sigma div by zero error
Expresses in melt and sparkle when pushing Strobe Blur to Zero.
Could change range of the melt and sparkle slider, but leaves this land mine for other usage, which is currently limited
0.00001 value is entirely arbitrary
> _gaussian_kernel1d() div zero crash, melt and sparkle

- ledfx/__main__.py
- ledfx/utils.py
Fix pystray icon being made visible out of runtime context
See hints at https://github.com/moses-palmer/pystray/issues/6
Also Fix relative path construct to be normalised. No impact to psytray but bad example and breaks notify-py
This has been improved to move the icon file path generation out to a util function of get_icon_path
this can be reused elsewhere. It does depend on utils.py being in the code ledfx folder parrallel to the icons folder, but it puts this pathing dependency in one place.
Tested with the --tray icon
Also tested by adding notifcation into the virtual_effects rest api and posting a notification ( code not included in this PR )
> Fix tray icon and allow latest psytray lib usage, add get_icon_path()

- .github/workflows/ci-build.yml
Upgrade actions to latest releases for setup-python and checkout to remove deprecation warnings that were soon to become errors
ci-builds now run clean
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2.2.1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.Show less
Build LedFx (Ubuntu) (3.9)The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Remove CI build deprecation warnings

- ledfx/__main__.py
Add mutually exclusive --no-tray to a group which now includes pre-existing --tray args
Attempting to launch with both with be rejected with standard args error against mutually excluded options Launching with neither will obey frozen state logic Otherwise as it says on the tin.
Modified help text as it made no sense to me.
Tested in dev builds only in --tray, --no-tray and the rejection of both
> add --no-tray launch option to core

- ledfx/__main__.py
Implemented while looking at why zeroconf / auto wled detect is broken between 0.30.0 and 0.47.0 zeroconf
Sample output with -vv arg
[DEBUG   ] __main__                       : Windows : 10 : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
[DEBUG   ] __main__                       : 3.11.0 : ('main', 'Oct 24 2022 18:26:48') : CPython
[DEBUG   ] __main__                       : Packages
[DEBUG   ] __main__                       : Cython : 0.29.32
[DEBUG   ] __main__                       : Pillow : 9.3.0
[DEBUG   ] __main__                       : PyJWT : 2.6.0
[DEBUG   ] __main__                       : aiohttp : 3.8.3
[DEBUG   ] __main__                       : aiohttp-cors : 0.7.0
[DEBUG   ] __main__                       : aiosignal : 1.3.1
[DEBUG   ] __main__ …
> add debug for platform and python under DEBUG

- ledfx/devices/__init__.py
If you have he default "WLED" server name in WLED / Settings / User interface / Server Description existing code mangles this name with the last 6 digits of the mac address for differentiation. however, async update of the device details loses the mangle. The side effect is that although all effects work right to the light stirp there is no rendered effect in the browser.
Can't fully explain why just reapplying the mangled name where I do works, but I can't break it. Tried some other approaches and none of them worked!
Reapply the mangled name post async_initialise to ensure it is passed into device config and in the creation of the virtual.
Just trying in virtual only was not successful, must be re-applied before appending the device config. Displayed name is the mangled name
Tested with …
> Fix WLED named devices not rendering in browser

- requirements.txt
- setup.py
remover warning by upgrading requests
C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requestsinit.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Match some versions in setup.py to requirements.txt
> General clean

- ledfx/devices/wled.py
Fix corner case for no name on segments on wled which does not have a "n" key
> Fix missing seg name scenario

- ledfx/effects/__init__.py
Just don't run blur when we don't have enough pixels
Tested against virtuals with 1,2,3 and 4 pixels.
Would crash before, now does not
> Fix crash on less that 4 pixels and blur

- .github/workflows/ci-build.yml
Add numpy install to actions for windows and ubuntu to match working OSX
aubio build failure fallback has been removed from PIP so our builds started failing
> Fix failing CI builds due to aubio build failure

- ledfx/effects/audio.py
This will make the default input device the loopback of the default output.
Should only hit WASAPI (windows) - it will fallback to the default input device if the loopback is not found.
> Change default device to wasapi loopback

- ledfx/devices/nanoleaf.py
- ledfx/effects/metro.py
- ledfx/utils.py
Far more graceful disable of Bokeh graphing.
If the lib elements are not available to import at program start, try / except and set bokeh_available accordingly
In the Metro example that uses the graphing capability, if bokeh is NOT available, hide the capture button
To support bokeh graphs, simply pip install bokeh on a need basis...profit...
Tested by running with bokeh not in my virtual env, then with bokeh present, and removing again. Ensure it behaves as expected.
Also remove flake8 fails from nanoleaf
> Make bokeh graph support run time dependant

- ledfx/api/find_launchpad.py
- ledfx/api/find_openrgb.py
- ledfx/devices/launchpad_lib.py
find_openrgb
Optional params added to override default server:port of localhost:6742
Bare call will just query the local server
```GET http://localhost:8888/api/find_openrgb```
To override server and / or port use
```GET http://localhost:8888/api/find_openrgb?server=1.2.3.4&port=5678```
Response on no server running
```
{
"status": "error",
"error": "timed out"
}
```
Response on Server found but no devices
```
{
"status": "success",
"devices": []
}
```
response with devices
```
{
"status": "success",
"devices": [
{
"name": "ASRock Z370 Gaming K6",
"type": 0,
"id": 0,
"leds": 1
},
{
"name": "ASUS ROG STRIX 3080 O10G V2 WHITE",
"type": 2,
"id": 1,
"leds": 22
},
{
"name": "Razer Deathadder V2",
"type": 6,
"id": 2,
"leds": 2
}
]
}
```
find_launchpad
```
GET …
```
> add rest endpoint for find_openrgb and find_launchpad

- ledfx/devices/nanoleaf.py
- requirements.txt
- setup.py
bump rtmidi to 1.5.1 to pick up post fixes from rtmidi team for breakage in windows in 1.5.0
Originally intended to address
https://github.com/SpotlightKid/python-rtmidi/issues/115
Resolve build from source issues in 3.11 on MacOS
Was blocked on missing bin for windows in rtmidi 1.5.0 see https://github.com/SpotlightKid/python-rtmidi/issues/150
Tested good on 1.5.1 for windows with launchpad
Simply did not work on 1.5.0
> rtmidi bump to 1.5.1

- ledfx/api/find_launchpad.py
- ledfx/devices/launchpad.py
- ledfx/devices/launchpad_lib.py
Move basic define search and config to data driven
Move segment definition and flush within specific class instance, only Launchpad X implemented so far
Added Launchpad S detection but no supporting class, this will presently just break beyond detection
Tested with Launchpad X on windows, device creation, deletion, activation, with and without segments auto creation
Tested on unsported mk2 for default responses.
now supports return of device params on call to 
```http://localhost:8888/api/find_launchpad```
as per
```{
"status": "success",
"device": {
"pixels": 81,
"rows": 9,
"name": "Launchpad X",
"segments": [
[
"TopBar",
"mdi:table-row",
[
[
72,
> More sustainable launchpad support part 1

- ledfx/devices/__init__.py
- ledfx/virtuals.py
Fix poor handling of priority_virtual cache invalidation, which could lead to an orphaned device only taking updates from a virtual that could be deactivated. Therefore other virtuals would not get flushed.
A bare setting of _active to False instead of the deactivate call and a incorrect comparison to check if the priority_virtual was getting disabled, and therefore flush the cache properties of the device.
Tested by not being able to reproduce the original issue
Set 2 or 3 virtuals on a device
Turn them on and off in various orders and ensure the active virtuals are still rendered to device
It is not possible to know which virtual is the priority_virtual without invasive debug, so just fuzz them all!
> Fix orphaned devices with multiple virtuals

- ledfx/devices/__init__.py
Protect against access of priority_virtual.id when priority_virtual has not been initialised.
Race condition at start up for pixel rich system.
Reproducable with FPP @ 4096 + WLED @(500 + 100 + 400)
With copy and span virtuals in config
Without fix, reproducable crash.
With fix, starts healthy.
Fix is passive, in that for normal operation, nothing new happens, it can only defend against the crash condition.
> Protect against priority virtual race condition on startup crash

- ledfx/devices/__init__.py
- ledfx/devices/wled.py
- ledfx/utils.py
Default wled protocol to DDP for builds equal or greater to when it was added
https://github.com/Aircoookie/WLED/blob/main/CHANGELOG.md#build-2110060
Causes a lot of "my lights are out of sync" with UDP as default
Threw away a bunch of legacy protocol selection code comments that are just cruft now
The code changed in wled.py is for completeness, not to have two methods of checking builds, noting that the wled existing was using a strict comparison that would be incorrect for beta versions.
And yes, DDP addition is not strictly sync support...
> Default to DDP on WLED

- ledfx/devices/wled.py
change order of WLED protocols to force default to DDP on manual add device
default field appears to be ignored, so list order is the only thing that currently works
> Change order of WLED protocols for drop down to DDP default

- ledfx/devices/hue.py
- requirements.txt
Initial support for Philips Hue, via the Hue Entertainment API (UDP streaming).  Each light in a Hue Entertainment zone represents a single pixel.
This is working well for me, although usability Improvements or documentation may be required for users to obtain some of the necessary values (user_name, client_key).
As I saw some other interest in supporting Hue, I wanted to at least get this implementation out in the wild for consideration.
> Philips Hue Support

- ledfx/effects/bands_matrix.py
- ledfx/effects/blocks.py
- ledfx/effects/equalizer.py
Will add multiple effect fixes to this PR. 
All fixes are generated against poisoned configs that occur when finding a bad configuration against 3 leds, that can be seen to be valid after fix
bands matrix has same exposure as already fixed in bands, add cap to band count to led count
blocks has the same exposure as above, similar fix
equaliser has the same exposure as above, similar fix
Pass completed, all 2D effects had the weakness, all other effects appear good
> General led count crash fixes

- hiddenimports.py
- setup.py
Add missing `python-mbedtls`  to `setup.py` and hidden imports for pyinstaller build
> Fix installing from source using pip

- ledfx/api/scenes.py
This support for per virtual config is extensible.
Default behavior where there is no virtuals key field is as before
Where a virtuals key field is listed, then for all virtuals carried, if they are not empty, then they are added to the scene config and save.
There may need to be more future logic for virtual off etc. That will be across front end and back end but can be incrementally developed.
For Further Study
> Scene API support for per virtual

- ledfx/devices/launchpad.py
- ledfx/devices/launchpad_lib.py
Backbuffer render and switch is now the default
Old slow style code has been removed
Two switches added into the launchpad device config
Alpha to turn on risky alpha code, in this case running status write, which although seen to work, does not change the frame render time. This can ONLY be due to lower layer interlocks beyond our control.
Diagnostic to turn on FPS and frame render timing diagnostics. Don't want those left in by default.
Testing by Matt, seen to be functional
> Attempt at back buffer render for Lanchpad S

- ledfx/devices/__init__.py
Missing call to virtuals invalidate cached properties on new parent device config
Tested by adding debug code into WLED device flush function, debugging effective frame rate
Prior to fix would only transition on ledfx restart Now transitions when device config is changed
Fix is passive unless device config is updated, and absolute worst case introduces a new derivation of the relevant cached properties
> Fix live refresh rate update on edit device settings

- ledfx/devices/__init__.py
As per
https://github.com/LedFx/LedFx/issues/425
With 10+ segments in a virtual, adding more MAY cause a crash where the data being copied into to device range is empty and therefore is an incompatible shape. By checking for actual data as cheaply as reasonable this crash condition is now just a passive pass that is healthy the next time round the cycle.
It is likely always possible to trigger as a race condition, but becomes "likely" at 10+
Prior to fix, adding another virtual segment to a large span against my 4096 panel was a 50 / 50 crash scenario at 10+
With fix, I have been able to fill up the 4096 panel with 21 virtuals and confirm healthy render via use of pixels effect
> Prevent crash from race condition and empty virtual data

- ledfx/effects/temporal.py
- ledfx/virtuals.py
that could lead to CPU hogging and general cumulative damage
Effects were orphaned without being deactivated. We were just building new effect instances on top.
For temporal effects, threads would be left running servicing the effect themselves, with non trivial led counts, this could quickly exhaust CPU and lead to slow down across the system, as the threads could preempt all other behaviours.
For audio effects the registered effect handler would still be running, but there would not be extra context switching with thread servicing, just cumulative runtime, that would lead to a different kind of death.
Virtual segment edit scenario was exposing due to multiple effect switching from the front end and my large panel use case for that testing.
With this fix in place, I cannot slow the …
> Fix effect leakage on changing effects

- ledfx/virtuals.py
See
https://discord.com/channels/469985374052286474/1134310087461179402/1134310211239301120
This will protect virtuals / effects in general from segmentation updates via rest api context vs the virtual render context
However, it does not protect against effects that sniff the pixel_count within the audio update call back that runs in a different context, that is for FFS
An easy breakage can still be achieved with 
https://github.com/bigredfrog/LedFx/blob/main/ledfx/effects/power.py#L75
> Protect virtuals from render while the segment config is changed

- ledfx/effects/energy.py
- ledfx/effects/melt_and_sparkle.py
- ledfx/effects/pitchSpectrum.py
- ledfx/effects/spectrum.py
- ledfx/virtuals.py
Protect effect audio update callbacks from segment changes by having the segment change grab the pre-existing lock on their active effect, which is already used to protect audio update callback
This is the next set of protections where effects access pixel count data or similar from their audio callback, that gets modified by segment reconfiguration
Makes effects like Power solid under segment edit, where as prior they were easy to crash out
There are four effects remaining with their own crashes under segment edit, unrelated to this...
These have now been addressed, all are variants of filters not being reset in on_activate() or in the case of melt and sparkle a queue that is destroyed in deactivate, but only established in init
> Protect Audio update callback from segment changes

- ledfx/effects/__init__.py
Protect against effect deactivate as the effect render pipeline is entered.
Tested with power->energy effects as they are aggressive and access vars inside the audio service
500 + effect changes @ 500 ms with 0 transition time at 4096 pixels
256 effect changes @ 1000 ms with 500 ms dissolve transition
100+ segment edit test
> Yet another mutex corner

- ledfx/devices/__init__.py
Always invalidate virtuals cache on adding segments, prevents orphaned priority virtual problem
This only fires when adding segments, can only improve scenario so that the priority virtual is current
Protects against reproducible scenario when switching between overlaid virtuals towards a device.
priority_virtual value could become none if a flush hit prior to there being any defined segments, and would not be revisited. Would leave device rendering nothing.
This would also mean that adding any sgements later would never update the device refresh rate.
Tested with 1000 effect changes across 13 virtuals including various cross overs into the scenario of interest.
Everything is good after test session including the specific scenario addressed by fix.
> Protect against no priority virtual

- ledfx/virtuals.py
Currently, only when in expert mode, "virtuals" have a transition time of 0 by default. This maybe should be fixed too, but for now I've just fixed a ZeroDivisionError which is always good I guess...
Exception this fixes:
```
Aug 19 12:08:05 ledfx-server python3[58142]: Exception in thread Thread-2 (thread_function):
Aug 19 12:08:05 ledfx-server python3[58142]: Traceback (most recent call last):
Aug 19 12:08:05 ledfx-server python3[58142]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Aug 19 12:08:05 ledfx-server python3[58142]:     self.run()
Aug 19 12:08:05 ledfx-server python3[58142]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Aug 19 12:08:05 ledfx-server python3[58142]:     self._target(*self._args, **self._kwargs)
Aug 19 12:08:05 …
```
> Fixed ZeroDivisionError

- ledfx/effects/__init__.py
- ledfx/virtuals.py
dummy effect render pixels to protect transitions
handle clear_effect more like set_effect to ensure similar transition behavior
Tested with long transition times as per videos in https://discord.com/channels/469985374052286474/1142496786460721162/1142577077028135054
Also tested with zero transition time
Temporarily removed the divide by zero protection to ensure it was not handled better, but then put it back in.
> Better clear effect behaviour including transitions

- ledfx/effects/__init__.py
- ledfx/effects/audio.py
- ledfx/virtuals.py
Ramblings at
https://discord.com/channels/469985374052286474/1142496786460721162
FIXES
1) More atomic protection for audio data updated that may access pixel_count, so make sure the check for active is locked in with the call, so don't risk getting pre-empted in the gap..
2) Wrap effect deactivate so that all child and parent deactivate is protected under lock mutex, otherwise effects that deleted things in their own deactivate could be exposed to a render running in parrallel as those elements were deleted. Change all calls to effect deactivate to _deactivate
3) Add lock mutex to virtual.set_effect(), virtual.clear_effect(), virtual.clear_frame() as all of these manipulate _active_effect and _transition_effect and could set them to None while a frame_assemble was in flight
4) Move …
> Many more mutex protections

- ledfx/api/virtual.py
- ledfx/api/virtuals.py
- ledfx/virtuals.py
Stop virtual api get calls from crashing on DummyEffect
Changing scenes with long transitions is one way to trigger this, where devices moving to DummyEffect cause crash on api call until clear.
Just don't populate effect data if active_effect object type is DummyEffect
Also fix audio callback leakage AND temporal effect leakage on double transition calls, leads to build up of runtime on audio callbacks and eventually loss of fps as we max the thread.
Discussed at rambling length in 
https://discord.com/channels/469985374052286474/1143384042683772938
> Fix DummyEffect api issue and Audio Callback / Temporal leakage

- ledfx/virtuals.py
Changing segment counts can leave active transitions with shape mismatch as they try to use old virtual pixelcount vs new pixelcount during the numpy function manipulation, leading to a crash
As segment edit is a very intentional administrator level like edit, just flush the transition effect if it is active and avoid any possible side effects.
Testing
Manual and via postman rest api calls for easy reproduction.
Set a virtual with 5 second transition
Change effect
As the transition is still in effect, edit virtual segments
Before fix
Leads to crash as per https://github.com/LedFx/LedFx/issues/463
After fix, no crash, transition moves straigth to active effect
> Flush transition effects in a segment edit scenario

- requirements.txt
- setup.py
After struggling to install ledfx on my raspberry pi (with a fresh install of raspberry pi os) I diagnosed the issue to the inability of installing python-rtmidi on the rpi.
I opened an issue at the python-rtmidi repo (https://github.com/SpotlightKid/python-rtmidi/issues/176) and it has been solved in the new update 1.5.6
This merge also updates the dependency to use 1.5.6 in the requirements.txt and setup.py
This is my first time contributing so feedback about my pull request is always welcome!  :)
> Update rtMid dependency version to 1.5.6

- ledfx/effects/pixels.py
Improve pixel diagnostic effect for large runs. clip min step time to 0.1 seconds. Add number of pixels to render and step
Allows faster scan of large arrays using step size up to 32
> Pixel diag effect tweak

- ledfx/effects/__init__.py
- ledfx/effects/spectrum.py
As discussed in, along with video at
https://discord.com/channels/469985374052286474/1170158058173911130
A user was looking for color options on the spectrum effect, however, implementation is not really in the dimension of base colors, as it is 
RED a direct plot of freq response
GREEN some kind of difference between last frame freq powers and this frame
BLUE a decaying hostoric filter freq power, with a some clamping on attack, and slow decay
This PR adds a slider for all 6 combinations of mapping those 3 sources into RGB, so the underlying intent of this effect is not changed, we just have some new variations, where 0 is the original and default.
IMPORTANT: While testing isolated a crash in pitchSpectrum due to update_config() preempting a render() pass and flushing key vals to None …
> Add slider for melbank filter mapping into RGB channels

- requirements.txt
- setup.py
This need to remove python-mbedtls so if some one like hue need to compile python-mbedtls from source there is no binary on pypi.org
> drop python-mbedtls for linux/arm*

- ledfx/__main__.py
- ledfx/sentry_config.py
- requirements.txt
- setup.py
This change can now go in and have the same as existing behavior for pypi until we start injecting DSN for discord releases
Transaction reporting has been removed for releases, we don't farm that data yet.
We can leave pipy builds reporting to the existing backend
Add client key for the discord releases into 
Ledfx - the current pypi end point, uses key : 
https://691086dc4,,,
Ledfx-betas we can use for discord releases into 
https://4c17033f5...
Ledfx-betas-v2 can be for developer releases, and key is hard coded into this PR for such, by bumping const.py DEV to not zero
https://de9ea3e00f...
We should add filtering to Ledfx to discard 0.x incoming
All these keys can also be reworked easily.
> rework sentry, disable transactions for non dev.

- .github/workflows/ci-linting.yml
- .github/workflows/codeql-analysis.yml
- hiddenimports.py
- ledfx/effects/clone.py
- ledfx/effects/equalizer2d.py
- ledfx/effects/imagespin.py
- ledfx/effects/twod.py
All twod effects will now handle width / height that is the result of rotation
All final rendering will be into native resolution with no rescale / aliasing implications
implement self.matrix Image and self.m_draw ImageDraw in the base twod class
Use in inherited effects
Always render into an image at the rotation width / height to avoid aliasing on resize All buried in twod class
Move do_once into twod as a base class method
Testing all effects on 128x128 and 16x32 panels
Tested test and rotation in all effects
Generally played with features
> Better Matrix rotation handling for non square

- ledfx/devices/wled.py
Ensure Wled copies _destination address on resolved callback into subdevice _destination
Otherwise flush to wled device passed to subdevice flush had window of opportunity for _destination = None
> Prevent wled device crash on resync

- .github/workflows/ci-build-osx-arm.yml
Currently we only have 500 minutes/month of CI, so we can do this manually for now.
No reason we can't trigger it as part of release process in the future.
> Add FlyCI OS X (M1) CI

- ledfx/sentry_config.py
Hard coded sentry DSNs into sentry_config.py
Move to brand new key, in this case ledfx-v2-dev where intention is
If environment variable ENVIRONMENT is set to any other value than empty or "dev" the release DSN will be used.
ledfx-v2-rel
client key / DSN
https://dc6070345a8dfa1f2f24433d16f7a133@o482797.ingest.sentry.io/4506350233321472
Default is to assume "dev" DSN
ledfx-v2-dev
client key / DSN
https://b192934eebd517c86bf7e9c512b3888a@o482797.ingest.sentry.io/4506350241841152
Tested with --offline
Tested with forced crash using --sentry-crash-test
Tested for no ENVIRONMENT variable = dev key
Tested with ENVIRONMENT = "rel" = rel key
Crash traces seen in back end in correct db's
> New sentry implementation

- ledfx/core.py
- poetry.lock
- pyproject.toml
Now we're on python 3.9 or above we don't need to worry about hacky win32api calls for Control-C.
Works over here, but could do with some testing.
> Remove pywin32

- ledfx/sentry_config.py
Tested with injection into environment of IS_RELEASE=True
Note that environment vars are strings only, so set to anything other than case insensitive "False" to make release build
> switch sentry config to IS_RELEASE

- ledfx/api/presets.py
- ledfx/api/virtual_presets.py
This removes the last instances of `default_presets` and `custom_presets` that are leftover from a long time ago.
This breaks the frontend and any other clients using the HTTP API, but should simplify things moving forward (not having to remap from old name to new name forever etc)
This doesn't actually fix the bug that I was looking at/for [discord thread](https://discord.com/channels/469985374052286474/1173289949483761787)  - that's caused by the frontend incorrectly sending default_presets as the category for user presets.
I'll have a look at the frontend and see if I can learn enough to do a PR to it.
> ⚠️⚠️⚠️ Breaking: Update Presets/Virtuals API ⚠️⚠️⚠️

- .github/workflows/ci-build.yml
- .github/workflows/codeql-analysis.yml
Should save some time/energy when we multiple PRs/commits at the same time.
> Cancel duplicate CI jobs

- ledfx/devices/launchpad_lib.py
Tested on local Launchpad X to ensure that new inheritance of device type byte did not break anything
Tested with discord user on MiniMk3
We had LOTS of build problems, but I don't believes issues with this implementation
User confirmed pixels / metro behaviour
We did not get to matrix, but only because I believe that ledfx was not restarted after setting device rows to 9
With device rows set to 1 ( and you must restart ledfx after change ) you get a stripped effect instead of plasma for example.
Confident for this to go in
> Launchpad mini first cut, inherit for X

- ledfx/effects/clone.py
Looks like some instances of fun can lose _handles
> Extra Protection for Clone

- ledfx/api/find_devices.py
- ledfx/core.py
- ledfx/devices/__init__.py
- ledfx/virtuals.py
- ledfx/zeroconf.py
This is a biggish change to core Zeroconf functionality.
Tore out the blocking stuff and refactored all zeroconf into one file.
~~Also reeenabled the scan on startup that has been commented out.~~
Tested with my WLED devices and all seems fine.
If we want to keep the listener alive and have newly discovered devices automatically added that's doable, but I think for now on startup and on demand is likely enough.
Should fix the annoying zeroconf warning on shutdown and make the shutdown process faster.
> Migrate to AsyncZeroconf

- ledfx/devices/adalight.py
This pull request fixes a bug where the serial connection could be interrupted and any erroring devices would not be deactivated - they simply spam the error log on every call to flush.
The `flush` function has been updated to include a call to the `deactivate` method when a serial connection interruption occurs.
> Update serial device error handling

- ledfx/core.py
- ledfx/mdns_manager.py
This pull request removes the zeroconf.async_close() method from the core and replaces it with a shutdown event listener.
> Use LedFx_shutdown event in Zeroconf implementation

- ledfx/effects/__init__.py
This pull request fixes an issue where invalid schemas were not being caught in the Effect class.
Now, when updating the effect configuration, if an invalid schema is detected, a warning message is logged and the update is aborted.
> Catch invalid schemas in Effect class

- ledfx/effects/audio.py
Its possible to have NaN values in the return of the power funcs
This will cause a crash if the effect converts the result of a calc to an int.
Force return of 0.0 in case of NaN
Multiple hits across effects in Sentry
> Nan protection in get_freq_power

- ledfx/api/find_openrgb.py
Tested against timeout by turning off my openrgb server and doing the auto scan
> demote openrgb timeout errors to warnings

- ledfx/effects/audio.py
This isn't important, it's just not getting full frames of audio when init or changing devices in the middle of a frame.
> Change audio frame size mismatch logging level to debug

- ledfx/effects/glitch.py
Glitch can sometimes have pixels with really low saturation values - rather than trying to fix that (HSV math is incomprehensible to me) I'm just adding a setting that will clamp the saturation values at the end of pixel generation.
Default to 1 seems to make the effect a lot more vibrant (unsurprisingly)
> Add saturation threshold to Glitch effect

- .github/renovate.json
This pull request updates the automerge strategy to monthly. 
This change ensures that minor updates, linters, and branch automerge are still enabled, but the automerge will now happen on a monthly basis.
> Update automerge strategy to monthly

- .github/renovate.json
This pull request updates the renovate.json file to include new package rules. The new rules specify that minor and patch updates should be automatically merged every month, while major updates should be automatically merged every week.
> Update renovate.json with new package rules

- ledfx/effects/noise2d.py
using noise on a 1d strip causes a crash due to axis mismatch
Check axis count from squeeze and reshape if needed
Testing running 1d and 2d matrix in parallel, both with noise, crashed before, runs clean with
> Fix: 1d noise

- .github/workflows/ci-build.yml
- .github/workflows/test-build-binaries.yml
macos-latest now points to arm64 images - pinned to latest non-arm64 runner image.
> Force x64 macOS runners version to macos-13

- ledfx/virtuals.py
Addresses https://github.com/LedFx/LedFx/issues/950
The active key at the virtual level is used to control play / pause, as opposed to active_effect, which registers the effect that would otherwise play.
Create from config had no handling for the active key, so inherits active at virtual creation.
Adding this key handling will now allow ledfx to honor the persisted value of the active key at the virtual level
Of course _paused is something else!!!
Tested by changing virtual state to play / paused and ensuring on restart that play / pause and active effect are preserved
> honor the active key for virtuals, which is used to control pause / play

- ledfx/devices/packets.py
OpenRGB protocol version 3 ignored data length
now enforces packet length = data length
ledfx prior used data length as payload length excluding self
OpenRGB now enforces that payload length field must include self
Main docs
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Documentation/OpenRGBSDK.md
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Documentation/OpenRGBSDK.md#netpacketheader-structure
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Documentation/OpenRGBSDK.md#net_packet_id_rgbcontroller_updateleds
Code that now enforces allows a zero value, but otherwise must match
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/NetworkServer.cpp#L692
0:  ORGB    Magic value
4:  \x02\x00\x00\x00    Device index
8:  \x1a\x04\x00\x00    Packet ID (0x41a) = …
> Fix: OpenRGB data length field for 0.91+

- .github/workflows/ci-build.yml
- .github/workflows/test-build-binaries.yml
flyci are discontinuing their runner service.
Migrate to GH.
Thanks so much flyci, was a pleasure.
> chore: Update macOS runner in CI workflows

- ledfx/api/find_launchpad.py
This [refactoring](https://github.com/LedFx/LedFx/commit/451e2cb5a9166bbefe8d42550217898b8ed45ec9#diff-909e0222c479b6571d6551e2a3540839a2ae1abace7b8524ff30c5cfc02c5b36L35) removed the found device from the response
readded respecting the `request_success` interface
=> found device will be in `response.data` (in oppose to `response.device`)
> (fix) readd found device in response of find_launchpad

- docs/conf.py
as per
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/__init__.py#L25
> Fix: Remove deprecated get_html_theme_path() call
